name: split
description: Split.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^2.1.0
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7

  flutter:
    sdk: flutter

  flutter_svg: ^0.22.0
  package_info_plus: ^1.0.4
  shared_preferences: ^2.0.6

  equatable: ^2.0.3
  bloc_test: ^8.5.0
  flutter_bloc: ^7.3.2
  mocktail: ^0.2.0
  http: ^0.13.4
  json_annotation: ^4.3.0
  get_it: ^7.2.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.1
  build_runner: ^2.1.4
  mockito: ^5.0.16
  test: any

flutter:

  uses-material-design: true

  assets:
#    - assets/configuration/
    - assets/images/
#    - assets/strings/values-en/


